/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gss.box4lin.views;

import javax.swing.JTabbedPane;

/**
 *
 * @author glauber
 */
public class BoxFrameWizzard extends javax.swing.JFrame {

    /**
     * Creates new form BoxFrameWizzard
     */
    public BoxFrameWizzard() {
        initComponents();        
    }
    
    private void goToNextTab(JTabbedPane pane){
        int currentTab = pane.getSelectedIndex();
        
        if(currentTab < pane.getTabCount() - 1){
            pane.setSelectedIndex(currentTab + 1);
        }
    }
    
    private void goToPreviousTab(JTabbedPane pane){
        int currentTab = pane.getSelectedIndex();
        
        if(currentTab > 0){
            pane.setSelectedIndex(currentTab - 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneWizzard = new javax.swing.JTabbedPane();
        panelWelcome = new javax.swing.JPanel();
        welcomeNextButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        panelLogin = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginNextButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelAuthorize = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        authorizeNextButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        panelFinish = new javax.swing.JPanel();
        finishFinishButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeNextButton.setText("Next");
        welcomeNextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                welcomeNextButtonMouseReleased(evt);
            }
        });

        jTextPane2.setEditable(false);
        jTextPane2.setText("Welcome to Box4Lin App. This wizzard will help you setup your Box.net storage settings in a few steps. Hit 'Next' to continue.");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWelcomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(welcomeNextButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeNextButton)
                .addContainerGap())
        );

        tabbedPaneWizzard.addTab("Welcome", panelWelcome);

        jTextField1.setText("jTextField1");

        jPasswordField1.setText("jPasswordField1");

        loginNextButton.setText("Next");
        loginNextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginNextButtonMouseReleased(evt);
            }
        });

        jTextPane3.setEditable(false);
        jTextPane3.setText("Please type your Box.net username and password:");
        jScrollPane3.setViewportView(jTextPane3);

        jLabel1.setText("Username ou email:");

        jLabel5.setText("Password:");

        jLabel2.setText("Invalid username or password.");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loginNextButton))
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(loginNextButton)
                .addContainerGap())
        );

        tabbedPaneWizzard.addTab("Login", panelLogin);

        jTextPane1.setEditable(false);
        jTextPane1.setText("Now copy and paste the following URL on your browser to allow Box4Lin get your Box.net storage info. Click 'Next' after you login the site.");
        jScrollPane1.setViewportView(jTextPane1);

        authorizeNextButton.setText("Next");
        authorizeNextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                authorizeNextButtonMouseReleased(evt);
            }
        });

        jTextPane4.setContentType("text/html");
        jTextPane4.setEditable(false);
        jTextPane4.setText("<center><a href=\"http://www.box.net/api/1.0/auth/\">http://www.box.net/api/1.0/auth/zs4ytyoljyhqvxq5greyasfan6y236df</a></center>");
        jScrollPane4.setViewportView(jTextPane4);

        javax.swing.GroupLayout panelAuthorizeLayout = new javax.swing.GroupLayout(panelAuthorize);
        panelAuthorize.setLayout(panelAuthorizeLayout);
        panelAuthorizeLayout.setHorizontalGroup(
            panelAuthorizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuthorizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAuthorizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAuthorizeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(authorizeNextButton))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAuthorizeLayout.setVerticalGroup(
            panelAuthorizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuthorizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(authorizeNextButton)
                .addContainerGap())
        );

        tabbedPaneWizzard.addTab("Authorize", panelAuthorize);

        finishFinishButton.setText("Finish");

        jTextPane5.setEditable(false);
        jTextPane5.setText("Congratulations! You have configured your Box4lin succesfully.");
        jScrollPane5.setViewportView(jTextPane5);

        javax.swing.GroupLayout panelFinishLayout = new javax.swing.GroupLayout(panelFinish);
        panelFinish.setLayout(panelFinishLayout);
        panelFinishLayout.setHorizontalGroup(
            panelFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinishLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinishLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(finishFinishButton))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFinishLayout.setVerticalGroup(
            panelFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinishLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(finishFinishButton)
                .addContainerGap())
        );

        tabbedPaneWizzard.addTab("Finish", panelFinish);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneWizzard, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneWizzard, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void welcomeNextButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeNextButtonMouseReleased
        goToNextTab(tabbedPaneWizzard);
    }//GEN-LAST:event_welcomeNextButtonMouseReleased

    private void loginNextButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNextButtonMouseReleased
        goToNextTab(tabbedPaneWizzard);
    }//GEN-LAST:event_loginNextButtonMouseReleased

    private void authorizeNextButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorizeNextButtonMouseReleased
        goToNextTab(tabbedPaneWizzard);
    }//GEN-LAST:event_authorizeNextButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoxFrameWizzard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoxFrameWizzard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoxFrameWizzard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoxFrameWizzard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BoxFrameWizzard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorizeNextButton;
    private javax.swing.JButton finishFinishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JButton loginNextButton;
    private javax.swing.JPanel panelAuthorize;
    private javax.swing.JPanel panelFinish;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JTabbedPane tabbedPaneWizzard;
    private javax.swing.JButton welcomeNextButton;
    // End of variables declaration//GEN-END:variables
}
